# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(10, 30, 500, 500))
        self.label_image.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(530, 150, 241, 381))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setToolTipDuration(0)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setObjectName("stackedWidget")
        self.region_grow_3 = QtWidgets.QWidget()
        self.region_grow_3.setObjectName("region_grow_3")
        self.label = QtWidgets.QLabel(self.region_grow_3)
        self.label.setGeometry(QtCore.QRect(20, 40, 60, 16))
        self.label.setObjectName("label")
        self.region_grow = QtWidgets.QPushButton(self.region_grow_3)
        self.region_grow.setGeometry(QtCore.QRect(10, 150, 113, 32))
        self.region_grow.setObjectName("region_grow")
        self.std_decay = QtWidgets.QLineEdit(self.region_grow_3)
        self.std_decay.setGeometry(QtCore.QRect(20, 60, 113, 21))
        self.std_decay.setObjectName("std_decay")
        self.stackedWidget.addWidget(self.region_grow_3)
        self.level_set_2 = QtWidgets.QWidget()
        self.level_set_2.setObjectName("level_set_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.level_set_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.time_step = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.time_step.setObjectName("time_step")
        self.horizontalLayout_7.addWidget(self.time_step)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.epsilon = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.epsilon.setObjectName("epsilon")
        self.horizontalLayout_6.addWidget(self.epsilon)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.mu = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.mu.setObjectName("mu")
        self.horizontalLayout_5.addWidget(self.mu)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lambda1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lambda1.setObjectName("lambda1")
        self.horizontalLayout_8.addWidget(self.lambda1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.sigma = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sigma.setObjectName("sigma")
        self.horizontalLayout_3.addWidget(self.sigma)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.c0 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.c0.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.c0.setObjectName("c0")
        self.horizontalLayout_2.addWidget(self.c0)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.iter_num = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.iter_num.setObjectName("iter_num")
        self.horizontalLayout.addWidget(self.iter_num)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lambda2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lambda2.setObjectName("lambda2")
        self.horizontalLayout_9.addWidget(self.lambda2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.nu = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nu.setObjectName("nu")
        self.horizontalLayout_4.addWidget(self.nu)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.level_set = QtWidgets.QPushButton(self.level_set_2)
        self.level_set.setGeometry(QtCore.QRect(10, 340, 113, 32))
        self.level_set.setObjectName("level_set")
        self.stackedWidget.addWidget(self.level_set_2)
        self.rectify = QtWidgets.QWidget()
        self.rectify.setObjectName("rectify")
        self.gen_polygon = QtWidgets.QPushButton(self.rectify)
        self.gen_polygon.setGeometry(QtCore.QRect(30, 80, 113, 32))
        self.gen_polygon.setObjectName("gen_polygon")
        self.delete_polygon = QtWidgets.QPushButton(self.rectify)
        self.delete_polygon.setGeometry(QtCore.QRect(30, 190, 113, 32))
        self.delete_polygon.setObjectName("delete_polygon")
        self.stackedWidget.addWidget(self.rectify)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(550, 100, 184, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox)
        self.stackedWidget.raise_()
        self.label_image.raise_()
        self.horizontalLayoutWidget_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(".SF NS Display")
        font.setBold(True)
        font.setWeight(75)
        self.menufile.setFont(font)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionreset = QtWidgets.QAction(MainWindow)
        self.actionreset.setObjectName("actionreset")
        self.menufile.addAction(self.actionopen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionreset)
        self.menubar.addAction(self.menufile.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionreset)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_image.setText(_translate("MainWindow", "select a picture"))
        self.label.setText(_translate("MainWindow", "std decay"))
        self.region_grow.setText(_translate("MainWindow", "region grow"))
        self.std_decay.setText(_translate("MainWindow", "400"))
        self.label_7.setText(_translate("MainWindow", " timestep:"))
        self.time_step.setText(_translate("MainWindow", "0.1"))
        self.label_6.setText(_translate("MainWindow", "    epsilon:"))
        self.epsilon.setText(_translate("MainWindow", "2.0"))
        self.label_8.setText(_translate("MainWindow", "           mu:"))
        self.mu.setText(_translate("MainWindow", "1.0"))
        self.label_9.setText(_translate("MainWindow", "  lambda1:"))
        self.lambda1.setText(_translate("MainWindow", "1.0"))
        self.label_4.setText(_translate("MainWindow", "      sigma:"))
        self.sigma.setText(_translate("MainWindow", "3.0"))
        self.label_3.setText(_translate("MainWindow", "       steep:"))
        self.c0.setText(_translate("MainWindow", "2.0"))
        self.label_2.setText(_translate("MainWindow", "  iter num:"))
        self.iter_num.setText(_translate("MainWindow", "500"))
        self.label_10.setText(_translate("MainWindow", " lambda2:"))
        self.lambda2.setText(_translate("MainWindow", "1.0"))
        self.label_5.setText(_translate("MainWindow", "           nu:"))
        self.nu.setText(_translate("MainWindow", "0.003"))
        self.level_set.setText(_translate("MainWindow", "level set"))
        self.gen_polygon.setText(_translate("MainWindow", "gen shape"))
        self.delete_polygon.setText(_translate("MainWindow", "delete"))
        self.label_11.setText(_translate("MainWindow", "method:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "region grow"))
        self.comboBox.setItemText(1, _translate("MainWindow", "level set"))
        self.comboBox.setItemText(2, _translate("MainWindow", "rectify"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionreset.setText(_translate("MainWindow", "reset"))

